### ISSUE TITLE
Not working with SSMS v17.3

### ISSUE THREAD

**Issue by BogdanBigB** [nicholas-ross/SSMS-Schema-Folders#1]
Hi,

This solution is not working with SSMS v17.3.

Going to Tool->Options->SQL Server Object Explorer->"Schema Folders", I'm met with the message: "An error occurred loading this property page"

![image](https://user-images.githubusercontent.com/25581398/33469398-9f42b510-d69d-11e7-838b-dba7a6040649.png)

**Comment by nicholas-ross** [comment]
This is usually caused by windows security blocking dll files downloaded from the internet.

After downloading, you need to right click on the zip file and go to properties. You should then see a button or tick box to unblock.

After unblocking you can then extract the files.

You can also unblock the individual dll files that you have already extracted. You can't unblock multiple files at once and need to do them individually, which is why I recommend unblocking the zip instead.

If this doesn't solve the issue then we will need to get the ssms log file.

**Comment by BogdanBigB** [comment]
Thanks mate, that fixed it!
