### ISSUE TITLE
Package Did Not Load Correctly

### ISSUE THREAD

**Issue by kristianoye** [nicholas-ross/SSMS-Schema-Folders#10]
I am running MS Management Studio 2014 (12.0.2269) on Windows 10 Professional (Build 1809  17763.678).  I installed the extension in:

C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\Extensions\SSMS Schema Folders

But received an error when connecting to a database: " (see attached)

![ExtensionError](https://user-images.githubusercontent.com/9437527/64567963-588ab900-d30e-11e9-8a68-74c8c4ec53ac.png)

It sounds like a great extension when it works.

**Comment by kristianoye** [comment]
Note: I went to look at ActivityLog.xml but the file did not exist.

**Comment by nicholas-ross** [comment]
Known Issues - Load Error
The first time SSMS is run with the extension it will show an error message. Click 'No' and restart SSMS. The included reg file sets the same registry setting as when you click the no button.

This happens because earlier versions of SSMS don't have official support for extensions. I believe companies can contact Microsoft to get added to an explicit allow list or dll signing. This is no longer required for SSMS 18.

**Comment by baizini** [comment]
I am running SQL Server Management Studio 18 (version 15.0.18118.0) on Windows 10 Pro version 10.0.15063 Build 15063
I installed the extension folder in C:\Program Files (x86)\Microsoft SQL Server Management Studio 18\Common7\IDE\Extensions
I got the error on first loading and clicked No.  I restarted SSMS several times, however...

I now no longer get the error message but the extension does not seem to be working. For example...

![image](https://user-images.githubusercontent.com/23362106/65591783-d3ea9c80-df95-11e9-9ce8-6ffc549f5d4d.png)

**Comment by nicholas-ross** [comment]
Known Issues - Not running/No options
This happens when Windows security blocks running of .dll files downloaded from the internet. The install instructions include the steps required to allow them to run.

There are two ways to solve this. You can either unblock each .dll file in the SSMS Schema Folders folder or delete the extracted files and unblock the .zip file before installing again.

To unblock a file, right click on it and go to properties. You should see an unblock button or checkbox that you will need to click and then click ok. Unfortunately it won't let you unblock multiple selected files. If you are unblocking the .dll files, you will need to unblock them individually one at a time.

**Comment by kristianoye** [comment]
I updated to Microsoft SQL Management v18.2 and got the same issue.  I built the project from source and tried to deploy the DLLs to Server 2012 (I don't see the unblock option)

**Comment by nicholas-ross** [comment]
I've updated from 18.1 to 18.3 and everything still works ok.

All the dll files are required to be deployed together. .Net will check that all referenced files exist before loading. Then at runtime it will load the correct file when needed.

The unblock option only applies to downloaded files. You will not see it if you compile the files yourself.

**Comment by baizini** [comment]
I installed in another computer as suggested (i.e. unblocking the .zip file) and all worked as expected.  I am running SSMS 18 and no load error even when starting up SSMS for the first time after the extension folder was copied.  Apologies for raising a non-issue.

**Comment by kristianoye** [comment]
I was finally able to get it work.  Thanks so much for the help (sorry I did not close this out long ago).
